### ISSUE TITLE
四个插件翻译报错

### ISSUE THREAD

**Issue by cherub0507** [Integral-Tech/pot-app-translate-plugin-freedict#1]
![微信截图_20231016142513](https://github.com/Integral-Tech/pot-app-translate-plugin-freedict/assets/58015207/d4a57c75-2449-49d8-a696-1dcbeb46ae88)

如截图所示，Free Dictionary / ECDict / Lingva都报错，MOJi辞書直接没有任何反应

**Comment by Integral-Tech** [comment]
这是词典插件，不是翻译句子的插件。请输入**单词**或**短语**
